languageCode = "en-us"
#baseurl = "http://localhost:1313"
# I added these two lines so the 
# webserver can serve the pages 
# correctly. Don't worry about it!
baseurl = "https://charlatan.io/lee"
canonifyurls = true
title = "Lee Ogilvie's Site"
theme = "hugo-zen"
copyright = "2016 Lee Ogilvie"
pluralizelisttitles = false
[params]
  logo = "/images/logo.png"
  email = "ogilvie.lee@gmail.com"
